#   VCS_ID
#  $Filename:   makefile.mw
#  $Author  :   chas 
#  $Revision:   1.1  $
#  $Date:   25 Feb  1995 14:20:38  $
# 
# 	Copyright (c)	1995 by Secant Technologies
#
 
# Threads makefile for HighC  
# usage: make threads.exe

INCLUDE=$(HCDIR)\inc
INCLUDEPM=$(OPMBASE)\include

LIB=$(HCDIR)\lib
LIBPM=$(OPMBASE)\lib
HC=$(HCDIR)\bin\hc.exe

LIBS=$(LIBPM)\opmhci $(LIB)\hcctd $(LIB)\hctd $(LIB)\hcna $(LIB)\os2386
STARTUP=$(LIB)\startup $(LIB)\globinit

!IF "$(DEBUG)" == "ON"
CPPFLAGS=-g -I$(INCLUDE) -I$(INCLUDEPM)
LINKFLAGS=/noignore /noext /align:16 /pm:pm /debug /map
!ELSE
CPPFLAGS=-O -I$(INCLUDE) -I$(INCLUDEPM)
LINKFLAGS=/noignore /noext /align:16 /pm:pm /packdata
!ENDIF

.cpp.obj:
    $(HC) -c $(CPPFLAGS) $*.cpp

threads.exe: threads.obj threads.def
    link386 $(LINKFLAGS) $(STARTUP) threads,threads,,$(LIBS);

