#   VCS_ID
#  $Filename:   makefile
#  $Author  :   chas 
#  $Revision:   1.1  $
#  $Date:   25 Feb  1995 14:20:38  $
#
 
# Semdemo makefile for HighC  
# usage: make semdemo.exe

INCLUDE=$(HCDIR)\inc
INCLUDEPM=$(OPMBASE)\include

LIB=$(HCDIR)\lib
LIBPM=$(OPMBASE)\lib
HC=$(HCDIR)\bin\hc.exe

LIBS=$(LIBPM)\opmhci $(LIB)\hcctd $(LIB)\hctd $(LIB)\hcna $(LIB)\os2386
STARTUP=$(LIB)\startup $(LIB)\globinit

!IF "$(DEBUG)" == "ON"
CPPFLAGS=-g -I$(INCLUDE) -I$(INCLUDEPM)
LINKFLAGS=/noignore /noext /align:16 /pm:pm /debug /map
!ELSE
CPPFLAGS=-O -I$(INCLUDE) -I$(INCLUDEPM)
LINKFLAGS=/noignore /noext /align:16 /pm:pm /packdata
!ENDIF

.cpp.obj:
    $(HC) -c $(CPPFLAGS) $*.cpp

.rc.res:
    rc -r -i $(INCLUDEPM) -i $(INCLUDE)\os2 $*.rc $*.res

all: semdemo.exe

semdemo.exe: semdemo.obj semdemo.res semdemo.def
    link386 $(LINKFLAGS) semdemo $(STARTUP),,,$(LIBS);
    rc semdemo.res

semdemo.res: semdemo.rc semdemo.h

